# Generated by Django 2.1 on 2018-08-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='key',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
