# Generated by Django 2.1 on 2018-08-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0002_event_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
