# Generated by Django 2.1 on 2018-08-21 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0004_order_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 10, 9, 11, 7807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 10, 9, 11, 7780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 10, 9, 11, 8223, tzinfo=utc)),
        ),
    ]
